[build.environment]
NODE_VERSION = "16.13.0"
YARN_VERSION = "1.22.17"

[context.deploy-preview.environment]
IMAGE_HOST = ""

[context.branch-deploy.environment]
IMAGE_HOST = ""

[[headers]]
  for = "images/*"
    [headers.values]
    X-HEADER-TO-CHANGE = "hello world"
