[build.environment]
NODE_VERSION = "18.18.2"
YARN_VERSION = "1.22.17"

[[redirects]]
from = '/api/*'
status = 200
to = '/.netlify/functions/api/:splat'

[functions]
node_bundler = 'esbuild'

[[plugins]]
package = "netlify-plugin-cache"

[plugins.inputs]
paths = [
  "img", # Eleventy Image Disk Cache
  ".cache", # Remote Asset Cache
]
